# Generated by Django 6.0.7 on 2026-09-13 05:09

import easytenant.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, help_text='Unique identifier for this tenant, matching the JWT claim value.', max_length=64, unique=True, verbose_name='tenant ID')),
                ('db_alias', models.CharField(help_text="The Django DATABASES key this tenant maps to (e.g. 'tenant_east').", max_length=64, unique=True, verbose_name='database alias')),
                ('engine', models.CharField(default='django.db.backends.postgresql', max_length=128, verbose_name='engine')),
                ('name', models.CharField(max_length=128, verbose_name='database name')),
                ('host', models.CharField(max_length=256, verbose_name='host')),
                ('port', models.IntegerField(verbose_name='port')),
                ('user', models.CharField(max_length=128, verbose_name='user')),
                ('password', easytenant.encrypted_fields.EncryptedCharField(help_text='Stored encrypted at rest using Fernet.', max_length=256, verbose_name='password')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive tenants reject new requests with a 500 error.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tenant config',
                'verbose_name_plural': 'tenant configs',
                'db_table': 'easytenant_tenantconfig',
                'ordering': ['tenant_id'],
            },
        ),
    ]
